---
# Homepage configuration
# See https://fontawesome.com/icons for icons options

title: "Chaz's Server"
subtitle: "IDK, watch stuff"
logo: "assets/logo.png"
# icon: "fas fa-skull-crossbones" Optional icon
footer: '<p>Created with <span class="has-text-danger">❤️</span> with <a href="https://bulma.io/">bulma</a>, <a href="https://vuejs.org/">vuejs</a> & <a href="https://fontawesome.com/">font awesome</a> // Fork me on <a href="https://github.com/bastienwirtz/homer"><i class="fab fa-github-alt"></i></a></p>'  # set false if you want to hide it.

# Optional message
# message:
#   # url: https://....https://zwicker.me/homer/
#   style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
#   title: "Welcome !"
#   content: "If you have any questions on how to use this, shoot me a text."

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "ansible"
    icon: "fab fa-github"
    url: "https://github.com/bastienwirtz/homer"
    target: '_blank' # optionnal html a tag target attribute
  - name: "Wiki"
    icon: "fas fa-book"
    url: "https://www.wikipedia.org/"

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Movies/TV"
    icon: "fas fa-film"
    items:
      # - name: "Emby"
      #   logo: "assets/tools/emby.png"
      #   subtitle: "Watch Movies & TV Shows"
      #   url: "https://emby.zwicker.me/"

      - name: "Plex"
        logo: "assets/tools/plex.png"
        subtitle: "Watch Movies & TV Shows"
        url: "https://plex.zwicker.me/"

      - name: "Ombi"
        logo: "assets/tools/ombi.png"
        subtitle: "Request Movies & TV Shows"
        tag: ""
        # Optional tagstyle
        # Same styling options as the optional message.
        tagstyle: ""
        url: "https://ombi.zwicker.me/"

      - name: "SyncLounge"
        logo: "assets/tools/sync.png"
        subtitle: "Watch together"
        url: "https://sync.zwicker.me/"

  - name: "Administration"
    icon: "fas fa-toolbox"
    items:

      - name: "qBittorrent"
        logo: ""
        subtitle: "Torrent Client"
        url: "http://localhost:8080/"

      - name: "Radarr"
        logo: ""
        subtitle: "Movies Aggregator"
        url: "http://localhost:7878/"

      - name: "Sonarr"
        logo: ""
        subtitle: "TV Aggregator"
        url: "http://localhost:8989/"

      - name: "Jackett"
        logo: ""
        subtitle: "Link Aggregator"
        url: "http://localhost:9117/"
